INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (1, 1, 1, 500, 4); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (2, 2, 1, 6000, 5); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (3, 1, 2, 500, 1); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (4, 2, 2, 6000, 1); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (5, 3, 2, 3600, 1); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (6, 1, 3, 500, 9); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (7, 2, 3, 6000, 8); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (8, 1, 4, 500, 1); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (9, 2, 4, 6000, 1); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (10, 3, 4, 3600, 1); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (11, 1, 5, 500, 6); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (12, 2, 5, 6000, 1); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (13, 3, 5, 3600, 1); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (14, 1, 6, 500, 7); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (15, 2, 6, 6000, 6); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (16, 3, 6, 3600, 1); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (17, 1, 7, 500, 8); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (18, 2, 7, 6000, 9); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (19, 3, 7, 3600, 1); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (20, 1, 8, 500, 8); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (21, 2, 8, 6000, 9); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (22, 3, 8, 3600, 1); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (23, 1, 9, 500, 9); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (24, 2, 9, 6000, 9); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (25, 1, 10, 500, 9); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (26, 2, 10, 6000, 9); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (27, 1, 11, 500, 9); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (28, 2, 11, 6000, 9); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (29, 3, 11, 3600, 9); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (30, 1, 12, 500, 10); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (31, 2, 12, 6000, 10); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (32, 3, 12, 3600, 10); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (33, 1, 13, 500, 9); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (39, 1, 15, 500, 9); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (40, 2, 15, 6000, 9); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (41, 3, 15, 3600, 9); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (42, 1, 16, 500, 9); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (43, 3, 16, 3600, 9); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (44, 4, 16, 8100, 9); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (45, 1, 17, 500, 9); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (46, 2, 17, 6000, 9); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (47, 3, 17, 3600, 9); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (48, 1, 18, 500, 9); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (49, 2, 18, 6000, 9); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (50, 1, 19, 500, 2); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (51, 2, 19, 6000, 1); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (52, 1, 20, 500, 1); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (53, 2, 20, 6000, 10); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (54, 1, 21, 500, 10); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (55, 1, 22, 500, 10); GO
INSERT INTO [ManagerOrderDetail] ([detail_id], [product_id], [manager_order_id], [price], [quantity]) VALUES (56, 1, 23, 500, 1); GO
