INSERT INTO [OrderDetail] ([id], [order_id], [product_id], [discount_id], [price], [quantity]) VALUES (1, 1, 6, 1, 100, 8); GO
INSERT INTO [OrderDetail] ([id], [order_id], [product_id], [discount_id], [price], [quantity]) VALUES (2, 2, 6, 1, 100, 5); GO
INSERT INTO [OrderDetail] ([id], [order_id], [product_id], [discount_id], [price], [quantity]) VALUES (3, 2, 7, 1, 150, 1); GO
INSERT INTO [OrderDetail] ([id], [order_id], [product_id], [discount_id], [price], [quantity]) VALUES (4, 3, 6, 1, 100, 9); GO
INSERT INTO [OrderDetail] ([id], [order_id], [product_id], [discount_id], [price], [quantity]) VALUES (5, 3, 7, 1, 150, 1); GO
INSERT INTO [OrderDetail] ([id], [order_id], [product_id], [discount_id], [price], [quantity]) VALUES (6, 3, 3, 1, 400, 1); GO
INSERT INTO [OrderDetail] ([id], [order_id], [product_id], [discount_id], [price], [quantity]) VALUES (7, 4, 6, 1, 100, 1); GO
INSERT INTO [OrderDetail] ([id], [order_id], [product_id], [discount_id], [price], [quantity]) VALUES (8, 5, 6, 1, 100, 1); GO
INSERT INTO [OrderDetail] ([id], [order_id], [product_id], [discount_id], [price], [quantity]) VALUES (9, 7, 6, 1, 100, 2); GO
INSERT INTO [OrderDetail] ([id], [order_id], [product_id], [discount_id], [price], [quantity]) VALUES (10, 7, 7, 1, 150, 3); GO
INSERT INTO [OrderDetail] ([id], [order_id], [product_id], [discount_id], [price], [quantity]) VALUES (11, 8, 6, 1, 100, 1); GO
INSERT INTO [OrderDetail] ([id], [order_id], [product_id], [discount_id], [price], [quantity]) VALUES (12, 9, 6, 1, 100, 3); GO
INSERT INTO [OrderDetail] ([id], [order_id], [product_id], [discount_id], [price], [quantity]) VALUES (13, 9, 7, 1, 150, 1); GO
INSERT INTO [OrderDetail] ([id], [order_id], [product_id], [discount_id], [price], [quantity]) VALUES (14, 9, 3, 1, 400, 1); GO
INSERT INTO [OrderDetail] ([id], [order_id], [product_id], [discount_id], [price], [quantity]) VALUES (15, 9, 1, 1, 500, 1); GO
INSERT INTO [OrderDetail] ([id], [order_id], [product_id], [discount_id], [price], [quantity]) VALUES (16, 11, 6, 2, 100, 1); GO
INSERT INTO [OrderDetail] ([id], [order_id], [product_id], [discount_id], [price], [quantity]) VALUES (17, 12, 1, 2, 500, 2); GO
INSERT INTO [OrderDetail] ([id], [order_id], [product_id], [discount_id], [price], [quantity]) VALUES (18, 13, 2, 2, 600, 2); GO
INSERT INTO [OrderDetail] ([id], [order_id], [product_id], [discount_id], [price], [quantity]) VALUES (19, 14, 3, 2, 400, 1); GO
